package com.model;

/**
 * TChuangwei generated by MyEclipse Persistence Tools
 */

public class TChuangwei implements java.io.Serializable
{

	// Fields

	private Integer chuangweiId;

	private Integer chuangweiPrice;

	private String chuangweiType;

	private Integer chuangweiLast;
	
	private String del;
	
	// Constructors

	/** default constructor */
	public TChuangwei()
	{
	}

	/** full constructor */
	public TChuangwei(Integer chuangweiPrice, String chuangweiType, Integer chuangweiLast, String del)
	{
		this.chuangweiPrice = chuangweiPrice;
		this.chuangweiType = chuangweiType;
		this.chuangweiLast = chuangweiLast;
		this.del = del;
	}

	// Property accessors

		public Integer getChuangweiId()
		{
			return this.chuangweiId;
		}

		public void setChuangweiId(Integer chuangweiId)
		{
			this.chuangweiId = chuangweiId;
		}
		
		public Integer getChuangweiPrice()
		{
			return this.chuangweiPrice;
		}

		public void setChuangweiPrice(Integer chuangweiPrice)
		{
			this.chuangweiPrice = chuangweiPrice;
		}

		public String getChuangweiType()
		{
			return chuangweiType;
		}

		public void setChuangweiType(String chuangweiType)
		{
			this.chuangweiType = chuangweiType;
		}

		public Integer getchuangweiLast()
		{
			return this.chuangweiLast;
		}

		public void setchuangweiLast(Integer chuangweiLast)
		{
			this.chuangweiLast = chuangweiLast;
		}

		public String getDel()
		{
			return this.del;
		}

		public void setDel(String del)
		{
			this.del = del;
		}


}