package com.model;

/**
 * TKeshi generated by MyEclipse Persistence Tools
 */

public class TKeshi implements java.io.Serializable//启用序列化功能
{
	
	private Integer keshiId;

	private String keshiAnme;

	private String keshiJianjie;

	private String del;
	
	private int keshixiayisheng;

	private int keshixiachuangwei;
	// 构造函数
	public TKeshi()
	{
	}

	public TKeshi(String keshiAnme, String keshiJianjie, String del)
	{
		this.keshiAnme = keshiAnme;
		this.keshiJianjie = keshiJianjie;
		this.del = del;
	}

	//属性访问器
	public Integer getKeshiId()
	{
		return this.keshiId;
	}

	public void setKeshiId(Integer keshiId)
	{
		this.keshiId = keshiId;
	}

	public int getKeshixiayisheng()
	{
		return keshixiayisheng;
	}

	public void setKeshixiayisheng(int keshixiayisheng)//显示科室下医生人数
	{
		this.keshixiayisheng = keshixiayisheng;
	}
	
	public int getKeshixiachuangwei()//显示科室下床位数
	{
		return keshixiachuangwei;
	}

	public void setKeshixiachuangwei(int keshixiachuangwei)
	{
		this.keshixiachuangwei = keshixiachuangwei;
	}

	public String getKeshiAnme()
	{
		return this.keshiAnme;
	}

	public void setKeshiAnme(String keshiAnme)
	{
		this.keshiAnme = keshiAnme;
	}

	public String getKeshiJianjie()
	{
		return this.keshiJianjie;
	}

	public void setKeshiJianjie(String keshiJianjie)
	{
		this.keshiJianjie = keshiJianjie;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}