package com.model;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable
{

	// Fields

	private Integer liuyanId;

	private String liuyanTitle;

	private String liuyanContent;
	
	private String liuyanDate;
	
	private String liuyanUser;
	
//	private String liuyanHuifu;

	// Constructors

	/** default constructor */
	public TLiuyan()
	{
	}

	/** full constructor */
	public TLiuyan(String liuyanTitle, String liuyanContent)//,String liuyanHuifu)
	{
		this.liuyanTitle = liuyanTitle;
		this.liuyanContent = liuyanContent;
//		this.liuyanHuifu = liuyanHuifu;
	}

	// Property accessors
	public Integer getLiuyanId()
	{
		return this.liuyanId;
	}	

	public String getLiuyanTitle()
	{
		return this.liuyanTitle;
	}

	public String getLiuyanUser()
	{
		return liuyanUser;
	}
	
//	public String getLiuyanHuifu()
//	{
//		return liuyanHuifu;
//	}
//	
	
	public String getLiuyanDate()
	{
		return liuyanDate;
	}

	public String getLiuyanContent()
	{
		return this.liuyanContent;
	}
	
	//set
	public void setLiuyanId(Integer liuyanId)
	{
		this.liuyanId = liuyanId;
	}
	
	public void setLiuyanUser(String liuyanUser)
	{
		this.liuyanUser = liuyanUser;
	}
	
//	public void setLiuyanHuifu(String liuyanHuifu)
//	{
//		this.liuyanHuifu = liuyanHuifu;
//	}

	public void setLiuyanDate(String liuyanDate)
	{
		this.liuyanDate = liuyanDate;
	}

	public void setLiuyanTitle(String liuyanTitle)
	{
		this.liuyanTitle = liuyanTitle;
	}

	public void setLiuyanContent(String liuyanContent)
	{
		this.liuyanContent = liuyanContent;
	}

}