package com.model;	

/**
 * TYisheng generated by MyEclipse Persistence Tools
 */

public class TYisheng implements java.io.Serializable
{

	// Fields

	private Integer yishengId;
	
	private String yishengPw;

	private String yishengName;

	private String yishengSex;

	private String yishengAge;

	private String yishengJianjie;
	
	private String yishengZhicheng;//
	
	private String yishengPhoto;//
	
	private String yishengZhuanchang;//

	private Integer keshiId;

	private String del;
	
	private String keshiName;

	// Constructors

	/** default constructor */
	public TYisheng()
	{
	}

	/** full constructor */
	public TYisheng(String yishengName, String yishengPw, String yishengSex, String yishengAge,
			String yishengJianjie, String yishengZhicheng,String yishengPhoto,String yishengZhuanchang,Integer keshiId, String del, String keshiName)
	{
		this.yishengName = yishengName;
		this.yishengPw = yishengPw;
		this.yishengSex = yishengSex;
		this.yishengAge = yishengAge;
		this.yishengJianjie = yishengJianjie;
		this.yishengZhicheng = yishengZhicheng;
		this.yishengPhoto = yishengPhoto;
		this.yishengZhuanchang = yishengZhuanchang;
		this.keshiId = keshiId;
		this.del = del;
		this.keshiName = keshiName;//
	}

	// Property accessors
	public String getYishengPw()
	{
		return this.yishengPw;
	}

	public void setYishengPw(String yishengPw)
	{
		this.yishengPw = yishengPw;
	}
	
	public String getYishengZhicheng()
	{
		return this.yishengZhicheng;
	}

	public void setYishengZhicheng(String yishengZhicheng)
	{
		this.yishengZhicheng = yishengZhicheng;
	}
	
	public String getYishengPhoto()
	{
		return this.yishengPhoto;
	}

	public void setYishengPhoto(String yishengPhoto)
	{
		this.yishengPhoto = yishengPhoto;
	}
	
	public String getYishengZhuanchang()
	{
		return this.yishengZhuanchang;
	}

	public void setYishengZhuanchang(String yishengZhuanchang)
	{
		this.yishengZhuanchang = yishengZhuanchang;
	}
	
	public Integer getYishengId()
	{
		return this.yishengId;
	}

	public void setYishengId(Integer yishengId)
	{
		this.yishengId = yishengId;
	}

	public String getYishengName()
	{
		return this.yishengName;
	}

	public String getKeshiName()
	{
		return keshiName;
	}

	public void setKeshiName(String keshiName)
	{
		this.keshiName = keshiName;
	}

	public void setYishengName(String yishengName)
	{
		this.yishengName = yishengName;
	}

	public String getYishengSex()
	{
		return this.yishengSex;
	}

	public void setYishengSex(String yishengSex)
	{
		this.yishengSex = yishengSex;
	}

	public String getYishengAge()
	{
		return this.yishengAge;
	}

	public void setYishengAge(String yishengAge)
	{
		this.yishengAge = yishengAge;
	}

	public String getYishengJianjie()
	{
		return this.yishengJianjie;
	}

	public void setYishengJianjie(String yishengJianjie)
	{
		this.yishengJianjie = yishengJianjie;
	}

	public Integer getKeshiId()
	{
		return this.keshiId;
	}

	public void setKeshiId(Integer keshiId)
	{
		this.keshiId = keshiId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}