package com.model;

/**
 * TYuyue generated by MyEclipse Persistence Tools
 */

public class TYuyueZhuyuan implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer userId;

	private Integer chuangweiId;
	
	private String shijian;

	private Integer shijianSize;
	
//	private String del;
	
	private Integer chuangweiPrice;
	
	private String chuangweiType;

	private String userName;
	

	/** default constructor */
	public TYuyueZhuyuan()
	{
	}

	/** full constructor */
	public TYuyueZhuyuan(Integer userId, Integer chuangweiId, String shijian, Integer shijianSize)//, String del)
	{
		this.userId = userId;
		this.chuangweiId = chuangweiId;
		this.shijian = shijian;
		this.shijianSize = shijianSize;
//		this.del = del;
	}

	// Property accessors
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}

	
	public String getChuangweiType()
	{
		return chuangweiType;
	}
	public void setChuangweiType(String chuangweiType)
	{
		this.chuangweiType = chuangweiType;
	}
	
	public Integer getChuangweiPrice()
	{
		return chuangweiPrice;
	}
	public void setChuangweiPrice(Integer chuangweiPrice)
	{
		this.chuangweiPrice = chuangweiPrice;
	}
	

	public Integer getUserId()
	{
		return this.userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	

	public String getUserName()
	{
		return userName;
	}
	public void setUserName(String userName)
	{
		this.userName = userName;
	}
	

	public Integer getChuangweiId()
	{
		return this.chuangweiId;
	}
	public void setChuangweiId(Integer chuangweiId)
	{
		this.chuangweiId = chuangweiId;
	}
	

	public String getShijian()
	{
		return this.shijian;
	}	
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	

	public Integer getShijianSize()
	{
		return this.shijianSize;
	}	
	public void setShijianSize(Integer shijianSize)
	{
		this.shijianSize = shijianSize;
	}

//	
//	public String getDel()
//	{
//		return this.del;
//	}
//	public void setDel(String del)
//	{
//		this.del = del;
//	}
	
}